### ISSUE TITLE
 [BUG] npm run dont work

### ISSUE THREAD

**Issue by kalib-code** [DhiWise/dhiwise-nodejs#10]
### Current Behavior:
doing npm i && npm run start error 

### Expected Behavior:

its need to run as expected on the readme file 

### Steps To Reproduce:
<!--
Example: steps to reproduce the behavior:
1.  clone the repo and go to the directory
2. run npm I && npm run start 
3.  error 
4. 
$ npm i && npm run start
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nodejs-code-generator@0.0.0
npm ERR! Found: lerna@4.0.0
npm ERR! node_modules/lerna
npm ERR!   dev lerna@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer lerna@"^3.0.0" from cz-lerna-changelog@2.0.3
npm ERR! node_modules/cz-lerna-changelog
npm ERR!   dev cz-lerna-changelog@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\extalka\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\extalka\AppData\Local\npm-cache\_logs\2021-11-24T01_18_06_157Z-debug.log

Enviroments 
OS: Window 10 
NPM: 7.20.6
NODE: 14.17.5

Device: 
HP EliteBook
Window 10 PRO 
Intel x64 Intel i7-8650U 1.90GHz

**Comment by saloni137** [comment]
@kalib-code Thank you for reporting this bug. Can you please add your device information and the screenshot containing error?

**Comment by kalib-code** [comment]
> 

updated the device

**Comment by saloni137** [comment]
Sorry @kalib-code but I am not able to see any device information and screenshot. Please add it in issue description. Thank you

**Comment by kalib-code** [comment]
> Sorry @kalib-code but I am not able to see any device information and screenshot. Please add it in issue description. Thank you

you mean environment ?
updated it and here it is 
OS: Window 10 
NPM: 7.20.6
NODE: 14.17.5

**Comment by saloni137** [comment]
@kalib-code Also Can you please add the screenshot that contains error that you are getting.

**Comment by uclnj** [comment]
![image](https://user-images.githubusercontent.com/835685/143235850-669126f4-f9e8-42cf-a591-aa641dfa7469.png)

Same issue attempting to "npm i" - npm version is 8.1.4.

**Comment by ravisojitra** [comment]
@uclnj For a workaround, you can try the below command. It's working for me.
`npm install --force`

**Comment by kalib-code** [comment]
doing npm install --force still has an issue. 

![image](https://user-images.githubusercontent.com/17924045/143247450-07e168db-cd1f-402f-bbde-d00e0cf63459.png)

**Comment by ravisojitra** [comment]
@kalib-code Please can you remove your node_modules & package-lock.json file inside packages/server & packages/client folder? and then run `npm i --force && npm start` from root directory.

**Comment by kalib-code** [comment]
its now working thank you
