### ISSUE TITLE
:bug: Bug: Installtion failed due to internal jsonlint access

### ISSUE THREAD

**Issue by sandeepscet** [DhiWise/dhiwise-nodejs#17]
### Steps To Reproduce:
npm install

### Environment:
- OS: Windows 10
- Node: 14.17.3
- npm: 6.14.13

### Error
`npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/DhiWise/jsonlint.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/DhiWise/jsonlint.git/': SSL certificate problem: self signed certificate in certificate chain
npm ERR!
npm ERR! exited with error code: 128
`

### Note
It seems npm installtion is trying to pull repo from github. This will fail as organization firewall will block. Ideally repo should use jsonlint via package file

**Comment by ravisojitra** [comment]
@sandeepscet Thanks for raising issue. It looks like issue of git policy in your network and has nothing to do with the code. However, let me know if any of the below two commands work.

`npm config set strict-ssl false` 
OR
`npm config set registry http://registry.npmjs.org/`

**Comment by sandeepscet** [comment]
### npm config list

cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.14.13 node/v14.17.3 win32 x64"

msvs_version = "2017"
node_gyp = ""
python = "C:\\Program Files\\Python310\\python.exe"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; node bin location = C:\Program Files\nodejs\node.exe
; "npm config ls -l" to show all defaults.

### Error

npm ERR!
npm ERR! fatal: unable to access 'https://github.com/DhiWise/react-dropdown-tree-select.git/': SSL certificate problem: self signed certificate in certificate chain
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sandip\AppData\Roaming\npm-cache\_logs\2021-12-15T11_22_48_743Z-debug.log
lerna ERR! npm install exited 1 in 'nodejs-code-generator'
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/ npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-code-generator@0.0.0 install: `lerna clean -y && lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-code-generator@0.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
