### ISSUE TITLE
[BUG] Unable to move past onboarding

### ISSUE THREAD

**Issue by ubarua123** [DhiWise/dhiwise-nodejs#23]
As the title says :- 

1. I signed up, asked me a bunch of questions like company name, role etc.
2. I chose Android as the technology.
3. Asked me import a design, I selected, " I don't have a design" and so it gave me a choice to select Explore or Template.
4. I chose explore, selected 1 screen, pressed '+' and clicked on proceed.  
5. On clicking 'Proceed', it said "Application Added Successfully" and then it again goes back to onboarding! Back to step (2) all over again. This seems to be going in an infinite loop.

**Comment by ravisojitra** [comment]
@ubarua123 I’ve taken a look at it, and identified the issue. Now on to resolving it ASAP!
Meanwhile if you face any more issues, you can always post it on [DhiWise's Discord server](https://discord.gg/7RnzeGjh).
