### ISSUE TITLE
Will your other generators be available, for example for flutter in opensource ?

### ISSUE THREAD

**Issue by DenisVASI9** [DhiWise/dhiwise-nodejs#32]
Hi, I tested your generator for nodejs, it's pretty cool. We would like to use your other products on our servers, will they be in opensource or on-prem?

**Comment by ravisojitra** [comment]
@DenisVASI9 I'm glad that you found nodejs generator useful. However currently we are not looking to opensource flutter generator, but for now you can use DhiWise platform to generate flutter apps.

**Comment by DenisVASI9** [comment]
@ravisojitra Ok, I can't find the prices on your website, are you going to leave the app free?

**Comment by ravisojitra** [comment]
@DenisVASI9 For now you can use it free for any technologies.
