### ISSUE TITLE
[BUG] <title>npm i error

### ISSUE THREAD

**Issue by metinkun** [DhiWise/dhiwise-nodejs#33]
When i start npm i , after clonning repo , i get this error :

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nodejs-code-generator@0.0.0
npm ERR! Found: lerna@4.0.0
npm ERR! node_modules/lerna
npm ERR!   dev lerna@"^4.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer lerna@"^3.0.0" from cz-lerna-changelog@2.0.3
npm ERR! node_modules/cz-lerna-changelog
npm ERR!   dev cz-lerna-changelog@"^2.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

i am using intel mac , node version v16.15.0  , npm version 8.5.5

**Comment by saloni137** [comment]
The workaround for this is ```npm i --force```
