### ISSUE TITLE
[BUG] With latest node version 16.15.0 and npm version 8.5.5 even npm install -- force fails

### ISSUE THREAD

**Issue by vipulnagarwal** [DhiWise/dhiwise-nodejs#34]
### Current Behavior:
1) Clone this repo
2) did npm install -- force
3) expectation was to successful installing of all packages and project to be ready to run

### Expected Behavior:
npm install as well as npm install -- force booth are failing with error.

error with npm install
![image](https://user-images.githubusercontent.com/16859513/166459607-bbd2d60d-2c1d-4a1b-b571-5ec2d5e998df.png)

error with npm install -- force
![image](https://user-images.githubusercontent.com/16859513/166460012-e3d18bee-f43d-4835-9cac-30acad9fc20b.png)

### Environment:
- Node: 16.15.0
- npm: 8.5.5
- windows 10

**Comment by saloni137** [comment]
@vipulnagarwal The error you are getting with ```npm i --force``` is because you don't have access to Git in your network
